//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------
namespace SoonestShipmentTrackingWebsite.Views.Admin
{
    public partial class Reports
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.TextBox txtFromDate;
        protected global::System.Web.UI.WebControls.TextBox txtToDate;
        protected global::System.Web.UI.WebControls.Button btnGenerate;
        protected global::System.Web.UI.WebControls.Button btnExport;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litDelivered;
        protected global::System.Web.UI.WebControls.Literal litOutForDelivery;
        protected global::System.Web.UI.WebControls.Literal litIssues;
        protected global::System.Web.UI.WebControls.GridView gvReport;
    }
}
