//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoonestShipmentTrackingWebsite.Views
{


    public partial class Contact
    {

        /// <summary>
        /// pnlFormSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlFormSuccess;

        /// <summary>
        /// pnlFormError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlFormError;

        /// <summary>
        /// litFormError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFormError;

        /// <summary>
        /// pnlContactForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlContactForm;

        /// <summary>
        /// txtName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtName;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// txtPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>
        /// txtSubject control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSubject;

        /// <summary>
        /// txtMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMessage;

        /// <summary>
        /// btnSend control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSend;
    }
}
